"""added payment rate and client signature tables.

Revision ID: 0a65d0956321
Revises: 19930054d4ea
Create Date: 2026-04-21 15:41:58.056675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a65d0956321'
down_revision = '19930054d4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_rate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('appt_type', sa.VARCHAR(length=15), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_from', sa.DATETIME(), nullable=True),
    sa.Column('date_to', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_signature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('client_file_id', sa.INTEGER(), nullable=True),
    sa.Column('strokes', mysql.LONGTEXT(), nullable=False),
    sa.Column('canvas_width', sa.INTEGER(), nullable=True),
    sa.Column('canvas_height', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_file_id'], ['client_file.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_signature')
    op.drop_table('payment_rate')
    # ### end Alembic commands ###
