"""empty message

Revision ID: 17ebf518258f
Revises: 1c000a42d8ce
Create Date: 2026-03-14 21:07:42.611193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17ebf518258f'
down_revision = '1c000a42d8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('previous_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('current_hash', sa.CHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('billing_xml', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('case_worker', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regional_center_team', ['regional_center_team_id'], ['id'])

    with op.batch_alter_table('client_appt', schema=None) as batch_op:
        batch_op.create_unique_constraint('_therapist_client_appt_unique', ['therapist_id', 'client_id', 'start_datetime'])

    with op.batch_alter_table('user_expense', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_user_expense_user'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_expense', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_expense_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('client_appt', schema=None) as batch_op:
        batch_op.drop_constraint('_therapist_client_appt_unique', type_='unique')

    with op.batch_alter_table('case_worker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('billing_xml', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('billing_note', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_activity_log')
    # ### end Alembic commands ###
