"""making report sections encrypted columns nullable.

Revision ID: 19930054d4ea
Revises: fdeeae78b65f
Create Date: 2026-04-19 20:54:53.379975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19930054d4ea'
down_revision = 'fdeeae78b65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_eval_report_section', schema=None) as batch_op:
        batch_op.alter_column('text_nonce',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('encrypted_dek',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('dek_nonce',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_eval_report_section', schema=None) as batch_op:
        batch_op.alter_column('dek_nonce',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('encrypted_dek',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('text_nonce',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
