"""add billing code

Revision ID: 1c000a42d8ce
Revises: 601ae7e6d1b7
Create Date: 2026-01-13 10:41:23.447962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c000a42d8ce'
down_revision = '601ae7e6d1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_code', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_auth', schema=None) as batch_op:
        batch_op.drop_column('billing_code')

    # ### end Alembic commands ###
