"""empty message

Revision ID: 471ab3aac3d0
Revises: 17ebf518258f
Create Date: 2026-03-15 21:10:52.300801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '471ab3aac3d0'
down_revision = '17ebf518258f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=sa.VARCHAR(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
