"""added in top level template table with template items table for mapping template versions

Revision ID: 49edac67e75e
Revises: 01ed6f4b895b
Create Date: 2026-05-19 14:49:15.680639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49edac67e75e'
down_revision = '01ed6f4b895b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_report_template_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('evaluation_report_template_id', sa.INTEGER(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_report_template_id'], ['evaluation_report_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluation_report_template_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'evaluation_report_template', ['evaluation_report_template_id'], ['id'])
        batch_op.drop_column('report_template_version')

    with op.batch_alter_table('evaluation_report_template', schema=None) as batch_op:
        batch_op.drop_column('section_type')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_report_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('section_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))

    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_template_version', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('evaluation_report_template_id')

    op.drop_table('evaluation_report_template_item')
    # ### end Alembic commands ###
