"""adding in therapist hand signature block

Revision ID: 4ed4804f4358
Revises: f7c2ee7b1bcf
Create Date: 2026-04-24 10:38:01.952837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ed4804f4358'
down_revision = 'f7c2ee7b1bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strokes', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('canvas_width', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('canvas_height', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.drop_column('canvas_height')
        batch_op.drop_column('canvas_width')
        batch_op.drop_column('strokes')

    # ### end Alembic commands ###
