"""intial sync

Revision ID: 601ae7e6d1b7
Revises: 
Create Date: 2026-01-12 15:11:26.378270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '601ae7e6d1b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appt_type', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regional_center', ['regional_center_id'], ['id'])

    with op.batch_alter_table('billing_note', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'billing_xml', ['billing_xml_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_appt', ['client_appt_id'], ['id'])

    with op.batch_alter_table('billing_xml', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regional_center', ['regional_center_id'], ['id'])

    with op.batch_alter_table('case_worker', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regional_center', ['regional_center_id'], ['id'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('needs_appt_scheduled',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.SMALLINT(),
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.create_foreign_key(None, 'regional_center', ['regional_center_id'], ['id'])
        batch_op.create_foreign_key(None, 'therapist', ['therapist_id'], ['id'])
        batch_op.create_foreign_key(None, 'case_worker', ['case_worker_id'], ['id'])

    with op.batch_alter_table('client_appt', schema=None) as batch_op:
        # batch_op.create_unique_constraint('_therapist_client_appt_unique', ['therapist_id', 'client_id', 'start_datetime'])
        batch_op.create_foreign_key(None, 'therapist', ['therapist_id'], ['id'])
        batch_op.create_foreign_key(None, 'billing_xml', ['billing_xml_id'], ['id'])
        batch_op.create_foreign_key(None, 'appt_type', ['appt_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.alter_column('created_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_foreign_key(None, 'intern', ['intern_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_appt', ['client_appt_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('client_auth', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('client_background', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('client_eval', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_foreign_key(None, 'therapist', ['therapist_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_appt', ['client_appt_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('client_eval_answer', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client_eval', ['client_eval_id'], ['id'])
        batch_op.create_foreign_key(None, 'eval_question', ['eval_question_id'], ['id'])

    with op.batch_alter_table('client_eval_report_section', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evaluation_report_template_section', ['section_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'evaluation_subtest', ['eval_subtest_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_evaluation_report', ['report_id'], ['id'])

    with op.batch_alter_table('client_eval_subtest_lookup', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client_eval', ['client_eval_id'], ['id'])
        batch_op.create_foreign_key(None, 'eval_subtest', ['subtest_id'], ['id'])

    with op.batch_alter_table('client_evaluation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_appt', ['client_appt_id'], ['id'])
        batch_op.create_foreign_key(None, 'therapist', ['therapist_id'], ['id'])

    with op.batch_alter_table('client_evaluation_answer', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evaluation_question', ['question_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_evaluation', ['evaluation_id'], ['id'])

    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client_evaluation', ['evaluation_id'], ['id'])

    with op.batch_alter_table('client_goal', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('company_meeting', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('eval_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'eval_subtest', ['subtest_id'], ['id'])

    with op.batch_alter_table('eval_report', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client_eval', ['client_eval_id'], ['id'])

    with op.batch_alter_table('eval_subtest', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evaluation', ['eval_id'], ['id'])

    with op.batch_alter_table('evaluation_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evaluation_subtest', ['subtest_id'], ['id'])

    with op.batch_alter_table('evaluation_question_response', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evaluation_question', ['question_id'], ['id'])

    with op.batch_alter_table('evaluation_subtest', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evaluation_type', ['eval_type_id'], ['id'])

    with op.batch_alter_table('intern', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'therapist', ['therapist_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('meeting_user_lookup', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'company_meeting', ['meeting_id'], ['id'])

    with op.batch_alter_table('regional_center', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('regional_center_team', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regional_center', ['regional_center_id'], ['id'])

    with op.batch_alter_table('report_section', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'eval_report', ['eval_report_id'], ['id'])
        batch_op.create_foreign_key(None, 'eval_subtest', ['eval_subtest_id'], ['id'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('calendar_access',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.alter_column('first_time_login',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['session_token'])
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('user_expense', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('first_time_login',
               existing_type=sa.SMALLINT(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('calendar_access',
               existing_type=sa.SMALLINT(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('report_section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('regional_center_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('regional_center', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('meeting_user_lookup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('intern', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluation_subtest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluation_question_response', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluation_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('eval_subtest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('eval_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('eval_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('company_meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_goal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_evaluation_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_evaluation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_eval_subtest_lookup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_eval_report_section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_eval_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_eval', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('client_background', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client_auth', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('approved',
               existing_type=sa.SMALLINT(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    with op.batch_alter_table('client_appt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_therapist_client_appt_unique', type_='unique')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('needs_appt_scheduled',
               existing_type=sa.SMALLINT(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('case_worker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('billing_xml', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('billing_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appt_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
