"""empty message

Revision ID: 7b50e6c19f08
Revises: e4047ea7b738
Create Date: 2026-04-09 12:14:28.823226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b50e6c19f08'
down_revision = 'e4047ea7b738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_nonce', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('dek_nonce', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('nonce')

    with op.batch_alter_table('client_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_nonce', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('dek_nonce', sa.LargeBinary(), nullable=False))
        batch_op.alter_column('key_version',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('nonce')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nonce', sa.BLOB(), nullable=False))
        batch_op.alter_column('key_version',
               existing_type=sa.INTEGER(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('dek_nonce')
        batch_op.drop_column('file_nonce')

    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nonce', sa.BLOB(), nullable=False))
        batch_op.drop_column('dek_nonce')
        batch_op.drop_column('text_nonce')

    # ### end Alembic commands ###
