"""added company and version id to evaluation type

Revision ID: 837fd836b5bf
Revises: a16eda844000
Create Date: 2026-05-19 10:06:02.230734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837fd836b5bf'
down_revision = 'a16eda844000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_type', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
