"""empty message

Revision ID: 860dabbac739
Revises: 88e53b6676a5
Create Date: 2026-04-12 20:40:42.519216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '860dabbac739'
down_revision = '88e53b6676a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('encrypted_filename',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('readable_filename',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('client_file', schema=None) as batch_op:
        batch_op.alter_column('readable_filename',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('encrypted_filename',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
