"""making log resource id longer

Revision ID: 8d4a281f07cd
Revises: 4ed4804f4358
Create Date: 2026-05-06 15:27:53.704850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d4a281f07cd'
down_revision = '4ed4804f4358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.VARCHAR(length=255, collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=sa.VARCHAR(length=255, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
