"""Added signer_name text field to signature page

Revision ID: 96948f0880f6
Revises: 8d4a281f07cd
Create Date: 2026-05-12 17:00:50.947874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96948f0880f6'
down_revision = '8d4a281f07cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signer_name', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_signature', schema=None) as batch_op:
        batch_op.drop_column('signer_name')

    # ### end Alembic commands ###
