"""added template company_id and version to report template sections and the eval report

Revision ID: a16eda844000
Revises: f25592d90fe4
Create Date: 2026-05-16 22:47:20.191341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16eda844000'
down_revision = 'f25592d90fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_template_version', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('evaluation_report_template_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_report_template_section', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.drop_column('report_template_version')

    # ### end Alembic commands ###
