"""empty message

Revision ID: c0c467c362fe
Revises: f4c47476a589
Create Date: 2026-03-28 20:43:30.229482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0c467c362fe'
down_revision = 'f4c47476a589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('file_upload_dir_id', sa.INTEGER(), nullable=True),
    sa.Column('stored_filename', sa.TEXT(), nullable=False),
    sa.Column('readable_filename', sa.TEXT(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['file_upload_dir_id'], ['file_upload_dir.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('migrate_version')
    with op.batch_alter_table('billing_note', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_note', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('nonce', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('key_version', sa.String(length=255), nullable=True))

    with op.batch_alter_table('client_eval_report_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_text', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('nonce', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('key_version', sa.String(length=255), nullable=True))

    with op.batch_alter_table('report_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_text', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('nonce', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('key_version', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_section', schema=None) as batch_op:
        batch_op.drop_column('key_version')
        batch_op.drop_column('encrypted_dek')
        batch_op.drop_column('nonce')
        batch_op.drop_column('encrypted_text')

    with op.batch_alter_table('client_eval_report_section', schema=None) as batch_op:
        batch_op.drop_column('key_version')
        batch_op.drop_column('encrypted_dek')
        batch_op.drop_column('nonce')
        batch_op.drop_column('encrypted_text')

    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.drop_column('key_version')
        batch_op.drop_column('encrypted_dek')
        batch_op.drop_column('nonce')
        batch_op.drop_column('encrypted_note')

    with op.batch_alter_table('billing_note', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('client_file')
    # ### end Alembic commands ###
