"""empty message

Revision ID: e4047ea7b738
Revises: c0c467c362fe
Create Date: 2026-04-07 10:12:27.814182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4047ea7b738'
down_revision = 'c0c467c362fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.alter_column('key_version',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_appt_note', schema=None) as batch_op:
        batch_op.alter_column('key_version',
               existing_type=sa.INTEGER(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
