"""add encrypted json to report for saving report progress

Revision ID: f25592d90fe4
Revises: 96948f0880f6
Create Date: 2026-05-16 20:49:56.512542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25592d90fe4'
down_revision = '96948f0880f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_report_json', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('text_nonce', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_dek', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('dek_nonce', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('key_version', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_evaluation_report', schema=None) as batch_op:
        batch_op.drop_column('key_version')
        batch_op.drop_column('dek_nonce')
        batch_op.drop_column('encrypted_dek')
        batch_op.drop_column('text_nonce')
        batch_op.drop_column('encrypted_report_json')

    # ### end Alembic commands ###
