"""empty message

Revision ID: f4c47476a589
Revises: 471ab3aac3d0
Create Date: 2026-03-22 21:08:49.048253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4c47476a589'
down_revision = '471ab3aac3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=mysql.INTEGER(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=sa.VARCHAR(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
