"""changed singature to tie to an appt and not file or client.

Revision ID: f7c2ee7b1bcf
Revises: 0a65d0956321
Create Date: 2026-04-22 22:18:42.857105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7c2ee7b1bcf'
down_revision = '0a65d0956321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_appt_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('client_signature_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('client_signature_ibfk_2'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('client_file_id'))
        batch_op.create_foreign_key(None, 'client_appt', ['client_appt_id'], ['id'])
        batch_op.create_unique_constraint(None, ['client_appt_id'])
        batch_op.drop_column('client_file_id')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('client_signature_ibfk_1'), 'client_file', ['client_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('client_signature_ibfk_2'), 'client', ['client_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('client_file_id'), ['client_file_id'], unique=True)
        batch_op.drop_column('client_appt_id')

    # ### end Alembic commands ###
