"""added client middle name and full name property.

Revision ID: fdeeae78b65f
Revises: 860dabbac739
Create Date: 2026-04-16 21:07:41.265990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeeae78b65f'
down_revision = '860dabbac739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
